version: '3.8'

services:
  flask-app:
    build: ./spam-sniffer-backend
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - GOOGLE_CLIENT_SECRET=your_google_client_secret_file
    depends_on:
      - mongo
    volumes:
      - ./spam-sniffer-backend:/app

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  react-app:
    build: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - flask-app
    volumes:
      - ./frontend:/app

volumes:
  mongo-data:
    driver: local
